[package]
name = "clamav-rs-bindings"
version = "0.5.5"
authors = ["Jonas Zaddach <jonas.zaddach@gmail.com>"]
edition = "2018"

[dependencies]
windows = "0.10.0"

[build-dependencies]
windows = "0.10.0"
